runtime: python312

entrypoint: gunicorn -b :$PORT sportsball.main:app

includes:
  - env.yaml

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /favicon\.ico
    static_files: static/img/icon-48.png
    upload: static/img/icon-48\.png
    secure: always

  - url: /.*
    script: auto
    secure: always
