runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/icon-48.png
  upload: static/img/icon-48.png

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /.*
  script: sportsball.app
